[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.10.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[redirects]]
from = "/docs/dawn-wait/*"
to = "https://hiru-dawn-wait.netlify.com/dawn_wait/:splat"
status = 200

[[redirects]]
from = "/docs/*"
to = "https://hiru-cordis.netlify.com/:splat"
status = 200

[[redirects]]
from = "/demo/warp-petstore/*"
to = "https://hiru-warp-petstore.netlify.com/:splat"
status = 200
